[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
QuPhys = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"
